### PR TITLE
Added support for unix domain sockets

### PR DESCRIPTION
**Pull request by akalinux**
Happy new year.

I closed my last pull request because some unit tests failed on older machines.  I have updated the unit tests for older versions of perl.

Unix domain socket parsing code is unchanged.

### CODE REVIEW

**Comment by plicease** [comment]
I am not sure that is a legal URI?  I think the better way to handle this may be to have an option on `AnyEvent::WebSocket::Client::connect` that takes a local file for a unix domain socket and connect to that instead of what is specified in the URI.  For completeness it would also be good for it to accept a host/port combination.

**Comment by akalinux** [comment]
This is backwards compatible with the normal host/port syntax, so nothing is lost.  We simply gain Unix socket syntax. 

1. The first unit test set prove backwards compatibility.
2. The 2nd set of unit tests prove proper parsing of unux domain sockets.
3. The unit tests also prove forward and reverse syntax.
4. The existing argument structure is unchanged as well.

As far as legal syntax, Unix domain socket urls are uncommon, and often not implemented.  The syntax is legal, because it follows standard uri encoding and deciding rules.

**Comment by akalinux** [comment]
There are 2 valid syntax types for Unix domain sockets.

ws://unix%2F:%2Fsocket.sock/path
And
ws+unix://unix%2F:%2Fsocket.sock/path

Your module owns the first package namespace.  I will create the 2nd, but I think URI would need to be patched to use the 2nd syntax.

**Comment by akalinux** [comment]
Looks like URI translates + to _P, so it won't need to be patched.

**Comment by akalinux** [comment]
After some testing and review, the entire suite of WebSocket modules on CPAN would have to be changed to do this another way.  So yes, just adding support for unix domain sockets here, solves the issue!

**Comment by akalinux** [comment]
I have added URI::ws_Punix to cpan, it should show up in a day or so.

**Comment by plicease** [comment]
I do not believe these to be standard complaint URLs.  I believe the relevant RFCs are 6455 section 3 https://tools.ietf.org/html/rfc6455#section-3
and 3986 section 3.2 https://tools.ietf.org/html/rfc3986#section-3.2

**Comment by akalinux** [comment]
It matches completely with section 3.3.  WebSocket URIs

   This specification defines two URI schemes, using the ABNF syntax
   defined in RFC 5234 [RFC5234], and terminology and ABNF productions
   defined by the URI specification RFC 3986 [RFC3986].

          ws-URI = "ws:" "//" host [ ":" port ] path [ "?" query ]
          wss-URI = "wss:" "//" host [ ":" port ] path [ "?" queryIf we just take the rfc at face value it is valid.Host being unix/ and port being a path, both of which are URI encoded are perfectly compliant.Only in general URI context are ports mentioned as numbers, but paths are not explicitly forbidden either.  Proper encoding solves this problem by converting / to %2F.Thus giving us unix%2F for the host and %2Fpath.sock for the port.  This still matches all the forward and reverse rules.On Jan 12, 2019 8:45 PM, Graham✈️✈️ <notifications@github.com> wrote:I do not believe these to be standard complaint URLs.  I believe the relevant RFCs are 6455 section 3 https://tools.ietf.org/html/rfc6455#section-3
and 3986 section 3.2 https://tools.ietf.org/html/rfc3986#section-3.2

**Comment by plicease** [comment]
Okay.  Well I certainly read this:

rfc3986
```
3.2.3.  Port

   The port subcomponent of authority is designated by an optional port
   number in decimal following the host and delimited from it by a
   single colon (":") character.

      port        = *DIGIT

   A scheme may define a default port.  For example, the "http" scheme
   defines a default port of "80", corresponding to its reserved TCP
   port number.  The type of port designated by the port number (e.g.,
   TCP, UDP, SCTP) is defined by the URI scheme.  URI producers and
   normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.
```

to mean that the port needs to be a "number in decimal", and that it should not accept a path like value.  I am not sure that I agree with your assessment of the host part either tbh.  However, if you feel that to be incorrect then I encourage you to open a PR against the super-class here https://github.com/libwww-perl/URI/pulls .  If I am wrong, then I don't think it makes sense to make the fix here anyway.

I am more than happy to work with you on adjusting the `AnyEvent::WebSocket::Client` interface to work with unix domain sockets as I suggested earlier.

**Comment by akalinux** [comment]
Hmm,Well, let.me look at both options.On Jan 13, 2019 8:06 AM, Graham✈️✈️ <notifications@github.com> wrote:Okay.  Well I certainly read this:
rfc3986
3.2.3.  Port

   The port subcomponent of authority is designated by an optional port
   number in decimal following the host and delimited from it by a
   single colon (":") character.

      port        = *DIGIT

   A scheme may define a default port.  For example, the "http" scheme
   defines a default port of "80", corresponding to its reserved TCP
   port number.  The type of port designated by the port number (e.g.,
   TCP, UDP, SCTP) is defined by the URI scheme.  URI producers and
   normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.

to mean that the port needs to be a "number in decimal", and that it should not accept a path like value.  I am not sure that I agree with your assessment of the host part either tbh.  However, if you feel that to be incorrect then I encourage you to open a PR against the super-class here https://github.com/libwww-perl/URI/pulls .  If I am wrong, then I don't think it makes sense to make the fix here anyway.
I am more than happy to work with you on adjusting the AnyEvent::WebSocket::Client interface to work with unix domain sockets as I suggested earlier.

**Comment by akalinux** [comment]
ok,
So here is the pull request for AnyEvent;:WebSocket::ClientUnix Domain Socket Support by akalinux · Pull Request #42 · plicease/AnyEvent-WebSocket-Client

    On Sunday, January 13, 2019, 9:47:22 AM CST, Michael Shipper <mshipper@yahoo.com> wrote:  
 
 Hmm,

Well, let.me look at both options.


On Jan 13, 2019 8:06 AM, Graham✈️✈️ <notifications@github.com> wrote:


Okay. Well I certainly read this:

rfc3986
3.2.3.  Port

   The port subcomponent of authority is designated by an optional port
   number in decimal following the host and delimited from it by a
   single colon (":") character.

      port        = *DIGIT

   A scheme may define a default port.  For example, the "http" scheme
   defines a default port of "80", corresponding to its reserved TCP
   port number.  The type of port designated by the port number (e.g.,
   TCP, UDP, SCTP) is defined by the URI scheme.  URI producers and
   normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.

to mean that the port needs to be a "number in decimal", and that it should not accept a path like value. I am not sure that I agree with your assessment of the host part either tbh. However, if you feel that to be incorrect then I encourage you to open a PR against the super-class here https://github.com/libwww-perl/URI/pulls . If I am wrong, then I don't think it makes sense to make the fix here anyway.

I am more than happy to work with you on adjusting the AnyEvent::WebSocket::Client interface to work with unix domain sockets as I suggested earlier.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Hmm,


Well, let.me look at both options.

**Pull request closed without merging**
